# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

issues:
  max-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: configtesting
      linters:
        - goconst
    - linters:
        - staticcheck
      text: "SA1019: aws.Endpoint is deprecated"
    - linters:
        - staticcheck
      text: "SA1019: aws.EndpointResolverWithOptions is deprecated"
    - linters:
        - staticcheck
      text: "SA1019: aws.EndpointResolverWithOptionsFunc is deprecated"
    - linters:
        - staticcheck
      text: "SA1019: config.WithEndpointResolverWithOptions is deprecated"

linters:
  disable-all: true
  enable:
    - dogsled
    - errcheck
    - errname
    - exportloopref
    - goconst
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - mnd
    - staticcheck
    - tenv
    - unconvert
    - unparam
    - unused
    - typecheck
    - whitespace

linters-settings:
  goconst:
    ignore-tests: true
  mnd:
    ignored-functions:
      - strings.SplitN
      - strings.SplitAfterN
      - os.MkdirAll
