// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generator/main.go; DO NOT EDIT.

package endpoints

const (
	AwsPartitionID      = "aws"
	AwsCnPartitionID    = "aws-cn"
	AwsIsoPartitionID   = "aws-iso"
	AwsIsoBPartitionID  = "aws-iso-b"
	AwsIsoEPartitionID  = "aws-iso-e"
	AwsIsoFPartitionID  = "aws-iso-f"
	AwsUsGovPartitionID = "aws-us-gov"
)
