// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generator/main.go; DO NOT EDIT.

package endpoints

const (
{{- range .Partitions }}
    {{ .ID | IDToConstant}}PartitionID = "{{ .ID }}"
{{- end }}
)